version: '3'
services:
  mysql:
    image: "mysql:8.0"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=root
    volumes:
      - ./db/sql/ini:/docker-entrypoint-initdb.d
      - ./data/mysql-data:/var/lib/mysql  # 使用相对路径来存储 MySQL 数据
    networks:
      - agent
    healthcheck: # 添加健康检查
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      retries: 10
      timeout: 3s


  redis:
    image: 'redis:latest'
    ports:
      - "6379:6379"
    networks:
      - agent

  hn:
    image: "hn"
    ports:
      - "8080:8080"  # 将 hn 服务的 8080 端口映射到宿主机的 8080 端口
    depends_on:
      - mysql  # 确保 mysql 服务先启动
      - redis  # 确保 redis 服务先启动
    networks:
      - agent
    restart: unless-stopped  # 这里添加自动重启策略

networks:
  agent:
    driver: bridge  # 使用默认的桥接网络驱动