version: '3'
services:
  mysql:
    image: "mysql:8.0"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=root
    volumes:
      - ./db/sql/ini:/docker-entrypoint-initdb.d
      - ./data/mysql-data:/var/lib/mysql  # 使用相对路径来存储 MySQL 数据

  redis:
    image: 'redis:latest'
    ports:
      - "6379:6379"