// Code generated by hertz generator.

package hertz_gen

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _meetingMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getrelevanthighlightsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getmeetingminutesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createmeetingMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getmeetinglistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getmeetinginfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _chatmeetingMw() []app.HandlerFunc {
	// your code...
	return nil
}
